logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                orm:
                    jdbc:
                        bind: TRACE
        spring:
            btvnss12: DEBUG
spring:
    application:
        name: btvnss12
    data:
        web:
            pageable:
                default-page-size: 10
                max-page-size: 100
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 123
        url: jdbc:postgresql://localhost:5432/btvn?currentSchema=ss12
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
